name: Python package

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - run: |
        python -m pip install --upgrade pip
        python -m pip install isort
        python -m pip install .
    - uses: psf/black@stable
    - run: python -m isort -v --ac .
    - run: python -m unittest discover -v -f -s tests
