name: Python package

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v3
    - uses: pdm-project/setup-pdm@main
      with:
        python-version: "3.10"
    - run: pdm install
    # - uses: psf/black@stable
    - run: pdm run sort
    - run: |
        if [ "$(git status --porcelain)" != "" ]
        then
          git config --global user.name 'la-catalog';
          git commit -a -m "Fix format";
          git push;
        fi
    - run: pdm run tests
